---
- name: Linux OS Upgrade
  hosts: all
  gather_facts: yes
  become: no

  tasks:
        - name: Upgrade packages with DNF
          become: yes
          ansible.builtin.dnf:
            name: '*'
            state: latest
            update_cache: yes
            update_only: no
          register: reg_upgrade_ok
